Add: Allow customizing the entire default name
alphapapa/org-bookmark-heading pull request #7
Opened 2020-01-02 16:40 UTC by akirak

Hi, I wanted to customize the entire default name format, so I have added a new customizable variable.

2020-01-03 05:12 UTC, alphapapa commented
Hi Akira,

Thanks, this looks useful.  Would you mind giving me an example of what format you want to use in your config?  Maybe we should provide a few choices in addition to a custom function.

I'll post a few comments in a review.

2020-01-03 05:19 UTC, alphapapa requested changes
Thank you!

2020-01-03 05:19 UTC, alphapapa commented on org-bookmark-heading.el
> +         (name (funcall org-bookmark-heading-name-fn filename heading))
I noticed the indentation appears to change in the diff, which clued me into the fact that the original file had some tabs in it.  I don't know how they got there.  :)  I just pushed a commit that untabifies the whole file.  Would you mind rebasing please?

2020-01-03 05:19 UTC, alphapapa commented on org-bookmark-heading.el
> +(defun org-bookmark-heading-default-name (filename heading)
Nitpick: Let's call it `org-bookmark-heading-default-name-fn`.  I'm not sure, but I think that's more consistent with other instances I've seen of the pattern of having a custom function and a default choice.

2020-01-03 05:19 UTC, alphapapa commented on org-bookmark-heading.el
> +  "Return the default bookmark name.
Please use this as the docstring:
```
Return bookmark name for FILENAME and HEADING.
Intended as the default value for `org-bookmark-heading-name-fn'.
```

2020-01-03 05:19 UTC, alphapapa commented on org-bookmark-heading.el
> +  (let ((display-filename (funcall org-bookmark-heading-filename-fn filename)))
Since this is so simple, I think we can omit binding `display-filename` and just put the `funcall` in the `concat`.  :)

2020-01-03 07:15 UTC, akirak commented
Thank you for the code review. I have resolved the issues in your comments.

> Would you mind giving me an example of what format you want to use in your config? 

I have this experimental configuration now:

```emacs-lisp
(use-package org-bookmark-heading
  :after org
  :custom
  (org-bookmark-heading-filename-fn
   (defun akirak/org-bookmark-heading-filename (path)
     (let* ((path (expand-file-name path))
            (project (project-current))
            (dir (abbreviate-file-name (file-name-directory path)))
            (filename (file-name-nondirectory path))
            (root (car-safe (project-roots project))))
       (if root
           (f-relative path (f-parent root))
         path))))
  (org-bookmark-heading-name-fn
   (defun akirak/org-bookmark-heading (path heading)
     (let ((ancestors (org-get-outline-path)))
       (format "\"%s\" in %s%s"
               (substring-no-properties
                (org-link-display-format heading))
               (akirak/org-bookmark-heading-filename path)
               (if ancestors
                   (substring-no-properties
                    (concat ":" (org-format-outline-path
                                 (mapcar #'org-link-display-format ancestors)
                                 nil nil "/")))
                 ""))))))
```

It consists of the heading of the entry, the file path of the file (which actually starts from the project root), and the outline path to the entry in the file, in that order. An example bookmark name produced by this function is as follows:

> "Emacs packages" in notes/aux.org:Open source projects

I made this because some of my files contains multiple entries on the same subjects in different contexts, e.g. trying out Emacs packages and contributing to them. Apparently, bookmark names should contain outline paths, but since they tend to be long, I want to put them at the end, after the file name. I'm pretty sure I tend to complicate things and mess up, but I think it's useful in seeking out opportunities for pushing the limits.

2020-12-12 10:32 UTC, alphapapa commented
Hi Akira,

Sorry for overlooking this PR (I'm going through a list of old ones in chronological order).  Are you still interested in pursuing this change?

Thanks.

2020-12-12 11:31 UTC, akirak commented
> Are you still interested in pursuing this change?

Maybe no. I rely more on Org links than on Org bookmarks. This package is still sometimes useful, and it should be a built-in feature, but I don't care much about the default bookmark name.

2020-12-12 11:31 UTC, closed without merging

2020-12-12 11:41 UTC, alphapapa commented
Ok, since I'm satisfied with the existing behavior, I'll leave this PR closed.  If you or anyone else is interested in it in the future, feel free to comment and we can reopen it.